esphome:
  name: ld2410s

esp8266:
  board: d1_mini

logger:
  baud_rate: 0

api:

ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "LD2410S Fallback Hotspot"

captive_portal:

external_components:
  - source:
      type: git
      url: https://github.com/willy40/ESPHome-LD2410
      ref: ld2410s-support
    refresh: always
    components: [ld2410s]

uart:
  id: uart_bus
  tx_pin: TX
  rx_pin: RX
  baud_rate: 115200
  parity: NONE
  stop_bits: 1

ld2410s:
  id: ld2410s_radar
  uart_id: uart_bus

  has_target:
    name: "Has Target"

  last_command_success:
    name: "Last Command Success"

  distance:
    name: "Target Distance"

  max_distance_gate:
    name: "Max Distance Gate"

  min_distance_gate:
    name: "Min Distance Gate"

  none_duration:
    name: "None Duration"

  # read-only gate energy sensors
  gate_energy:
    - name: "Gate 0"
    - name: "Gate 1"
    - name: "Gate 2"
    - name: "Gate 3"
    - name: "Gate 4"
    - name: "Gate 5"
    - name: "Gate 6"
    - name: "Gate 7"
    - name: "Gate 8"
    - name: "Gate 9"
    - name: "Gate 10"
    - name: "Gate 11"
    - name: "Gate 12"
    - name: "Gate 13"
    - name: "Gate 14"
    - name: "Gate 15"

  # write sliders for saving gate energies
  gate_energy_write:
    - name: "Gate Write 0"
    - name: "Gate Write 1"
    - name: "Gate Write 2"
    - name: "Gate Write 3"
    - name: "Gate Write 4"
    - name: "Gate Write 5"
    - name: "Gate Write 6"
    - name: "Gate Write 7"
    - name: "Gate Write 8"
    - name: "Gate Write 9"
    - name: "Gate Write 10"
    - name: "Gate Write 11"
    - name: "Gate Write 12"
    - name: "Gate Write 13"
    - name: "Gate Write 14"
    - name: "Gate Write 15"

button:
  - platform: template
    name: "Enter Config Mode"
    on_press:
      - lambda: 'id(ld2410s_radar).set_config_mode(true);'

  - platform: template
    name: "Exit Config Mode"
    on_press:
      - lambda: 'id(ld2410s_radar).set_config_mode(false);'

  - platform: template
    name: "Get Config"
    on_press:
      - lambda: 'id(ld2410s_radar).query_parameters();'

  - platform: template
    name: "Switch to Standard Mode"
    on_press:
      - lambda: 'id(ld2410s_radar).switch_output_mode(true);'

  - platform: template
    name: "Switch to Minimal Mode"
    on_press:
      - lambda: 'id(ld2410s_radar).switch_output_mode(false);'